/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Client_2;

import Client_1.*;
import Client_2.Client_2;
import Server.*;
import java.awt.Dimension;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author This PC
 */
public class Recieve_Files_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Server_Content
     */
    public Recieve_Files_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recMsg = new javax.swing.JLabel();
        downloadBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fileLbl = new javax.swing.JLabel();
        locationLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("/\\ ... Incoming ... /\\");
            jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

            recMsg.setFont(new java.awt.Font("Sitka Display", 0, 36)); // NOI18N
            recMsg.setForeground(new java.awt.Color(204, 0, 0));
            jPanel1.add(recMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 490, 55));

            downloadBtn.setBackground(new java.awt.Color(255, 255, 255));
            downloadBtn.setFont(new java.awt.Font("Sylfaen", 0, 36)); // NOI18N
            downloadBtn.setForeground(new java.awt.Color(0, 0, 0));
            downloadBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/download.png"))); // NOI18N
            downloadBtn.setText("Download");
            downloadBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    downloadBtnActionPerformed(evt);
                }
            });
            jPanel1.add(downloadBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 260, 70));

            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shutdown.png"))); // NOI18N
            jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel5MouseClicked(evt);
                }
            });
            jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, 40));

            jLabel6.setFont(new java.awt.Font("Sylfaen", 0, 24)); // NOI18N
            jLabel6.setForeground(new java.awt.Color(204, 0, 0));
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/back.png"))); // NOI18N
            jLabel6.setText("Back");
            jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jLabel6MouseClicked(evt);
                }
            });
            jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 7, 114, 45));

            nameLbl.setFont(new java.awt.Font("Sitka Display", 0, 36)); // NOI18N
            nameLbl.setForeground(new java.awt.Color(51, 153, 255));
            jPanel1.add(nameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 490, 49));

            jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/45886907warning-yellow-blinking-sign-animated-gif-3 (1).gif"))); // NOI18N
            jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 530, 310));

            fileLbl.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
            fileLbl.setForeground(new java.awt.Color(204, 0, 0));
            jPanel1.add(fileLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 490, 30));

            locationLbl.setFont(new java.awt.Font("Sitka Display", 0, 24)); // NOI18N
            locationLbl.setForeground(new java.awt.Color(204, 0, 0));
            jPanel1.add(locationLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 490, 30));

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            );

            setBounds(700, 10, 543, 540);
        }// </editor-fold>//GEN-END:initComponents

    
    private void downloadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadBtnActionPerformed
        // TODO add your handling code here:
        String loc=locationLbl.getText();
        String name=nameLbl.getText();
        Download_Client downFileC=new Download_Client();
        
        downFileC.download(loc, name);
        
    }//GEN-LAST:event_downloadBtnActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
        super.dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    
    public void name(String details, String location, String name){
        System.out.println(name);
        recMsg.setText(details);
        nameLbl.setText(name);
        fileLbl.setText("Are You Sure, Want to DownLoad this ?");
        locationLbl.setText(location);
    }
    
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recieve_Files_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recieve_Files_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recieve_Files_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recieve_Files_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recieve_Files_GUI().setVisible(true);
            }
        });
        
        
        
        
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadBtn;
    public static javax.swing.JLabel fileLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel locationLbl;
    public static javax.swing.JLabel nameLbl;
    public javax.swing.JLabel recMsg;
    // End of variables declaration//GEN-END:variables
}
